#pragma once

#define COLOR_BLACK   0x00
#define COLOR_BLUE    0x01
#define COLOR_GREEN   0x02
#define COLOR_CYAN    0x03
#define COLOR_RED     0x04
#define COLOR_MAGENTA 0x05
#define COLOR_YELLOW  0x06
#define COLOR_WHITE   0x07
#define COLOR_BRIGHT  0x08


#define MAKECOLOR(bkg, frg) ((bkg << 4) | frg)


#define COLOR_GRID         MAKECOLOR(COLOR_BLACK | COLOR_BRIGHT, COLOR_BLACK)
#define COLOR_WALL         MAKECOLOR(COLOR_BLACK, COLOR_WHITE | COLOR_BRIGHT)
#define COLOR_RANGE        MAKECOLOR(COLOR_BLUE, COLOR_WHITE | COLOR_BRIGHT)
#define COLOR_CURSOR       MAKECOLOR(COLOR_GREEN, COLOR_WHITE | COLOR_BRIGHT)
#define COLOR_ATTACK_RANGE MAKECOLOR(COLOR_CYAN, COLOR_WHITE | COLOR_BRIGHT)
